In [1]:
import pyarrow.parquet as pq
import polars as pl
pl.Config.set_tbl_cols(40)          # Show up to 20 columns
pl.Config.set_tbl_rows(80)   
pl.Config.set_tbl_width_chars(500)  # Make the table wider in the console
pl.Config.set_fmt_str_lengths(50)   # Don't cut off long strings like stoch_key

results_path = r'C:\Users\Owner\airflow-trading\data_lake\Opt_Session_20260427_110253_01\master_metrics.parquet'

# Open the file metadata
parquet_file = pq.ParquetFile(results_path)

df_master = pl.read_parquet(results_path)

# 1. Get Row Count
print(f"Total Rows: {parquet_file.metadata.num_rows}")

# 2. Get Schema
print("Master Data Schema:")
print(parquet_file.schema)

Total Rows: 12600
Master Data Schema:
<pyarrow._parquet.ParquetSchema object at 0x000002DDCFC44800>
required group field_id=-1 schema {
  optional int32 field_id=-1 regime_id;
  optional int32 field_id=-1 signal_layer (Int(bitWidth=8, isSigned=true));
  optional binary field_id=-1 signal_scope_id (String);
  optional int64 field_id=-1 era_int;
  optional int32 field_id=-1 exit_window_h;
  optional float field_id=-1 SL;
  optional float field_id=-1 TP;
  optional boolean field_id=-1 use_trailing_sl;
  optional float field_id=-1 trailing_sl_pct;
  optional int32 field_id=-1 trailing_sl_interval;
  optional boolean field_id=-1 trailing_sl_stop_at_pos;
  optional boolean field_id=-1 use_limit_entry;
  optional int32 field_id=-1 limit_order_expiry_bars;
  optional boolean field_id=-1 trade_overlap;
  optional boolean field_id=-1 trade_flip_on_entry;
  optional int32 field_id=-1 trade_window_interval;
  optional int32 field_id=-1 total_pos;
  optional int32 field_id=-1 win_pos;
  optional float field_id=-1 balance;
  optional float field_id=-1 max_drawdown;
  optional int32 field_id=-1 max_consecutive_losses;
  optional binary field_id=-1 signal_json (String);
}

In [7]:
# Aggregate with Drawdown metrics and strict consistency filter
robust_combos_with_risk = (
    df_master
    .filter(pl.col("trade_overlap") == True)
    .group_by([
        "regime_id", "signal_layer", "signal_scope_id", "exit_window_h", 
        "SL", "TP", "use_trailing_sl", "trade_flip_on_entry"
    ])
    .agg(
        pl.col("balance").mean().alias("avg_balance"),
        pl.col("balance").min().alias("min_era_balance"),
        pl.col("max_drawdown").max().alias("worst_drawdown"), # The deepest dip ever recorded
        pl.col("max_drawdown").mean().alias("avg_drawdown"),
        pl.col("era_int").n_unique().alias("total_eras"),
        pl.col("total_pos").sum().alias("total_trades")
    )
    .filter(pl.col("min_era_balance") >= 100)
    .sort("avg_balance", descending=True)
)

print("Robust Combos (Min Balance > ) ranked by Avg Balance with Drawdown:")
print(robust_combos_with_risk)

Robust Combos (Min Balance > ) ranked by Avg Balance with Drawdown:
shape: (8, 14)
┌───────────┬──────────────┬──────────────────┬───────────────┬─────┬─────┬─────────────────┬─────────────────────┬─────────────┬─────────────────┬────────────────┬──────────────┬────────────┬──────────────┐
│ regime_id ┆ signal_layer ┆ signal_scope_id  ┆ exit_window_h ┆ SL  ┆ TP  ┆ use_trailing_sl ┆ trade_flip_on_entry ┆ avg_balance ┆ min_era_balance ┆ worst_drawdown ┆ avg_drawdown ┆ total_eras ┆ total_trades │
│ ---       ┆ ---          ┆ ---              ┆ ---           ┆ --- ┆ --- ┆ ---             ┆ ---                 ┆ ---         ┆ ---             ┆ ---            ┆ ---          ┆ ---        ┆ ---          │
│ i32       ┆ i8           ┆ str              ┆ i32           ┆ f32 ┆ f32 ┆ bool            ┆ bool                ┆ f32         ┆ f32             ┆ f32            ┆ f32          ┆ u32        ┆ i32          │
╞═══════════╪══════════════╪══════════════════╪═══════════════╪═════╪═════╪═════════════════╪═════════════════════╪═════════════╪═════════════════╪════════════════╪══════════════╪════════════╪══════════════╡
│ 133       ┆ 1            ┆ lookback__5m__u1 ┆ 2             ┆ 0.2 ┆ 0.8 ┆ false           ┆ false               ┆ 106.401047  ┆ 100.469818      ┆ 0.029639       ┆ 0.020777     ┆ 12         ┆ 1227         │
│ 301       ┆ 1            ┆ lookback__5m__u1 ┆ 2             ┆ 0.4 ┆ 0.6 ┆ false           ┆ false               ┆ 105.823708  ┆ 100.321312      ┆ 0.044319       ┆ 0.029024     ┆ 12         ┆ 1212         │
│ 91        ┆ 1            ┆ lookback__5m__u1 ┆ 2             ┆ 0.2 ┆ 0.6 ┆ false           ┆ false               ┆ 105.38134   ┆ 101.147491      ┆ 0.034536       ┆ 0.019745     ┆ 12         ┆ 1231         │
│ 119       ┆ 1            ┆ lookback__5m__u1 ┆ 4             ┆ 0.2 ┆ 0.6 ┆ false           ┆ false               ┆ 105.078636  ┆ 100.448563      ┆ 0.036129       ┆ 0.022607     ┆ 12         ┆ 1209         │
│ 175       ┆ 1            ┆ lookback__5m__u1 ┆ 2             ┆ 0.2 ┆ 1.0 ┆ false           ┆ false               ┆ 104.994553  ┆ 102.053246      ┆ 0.041661       ┆ 0.022733     ┆ 12         ┆ 1224         │
│ 637       ┆ 1            ┆ lookback__5m__u1 ┆ 2             ┆ 0.8 ┆ 0.2 ┆ false           ┆ false               ┆ 104.431519  ┆ 100.145691      ┆ 0.051393       ┆ 0.027351     ┆ 12         ┆ 1236         │
│ 179       ┆ 1            ┆ lookback__5m__u2 ┆ 2             ┆ 0.2 ┆ 1.0 ┆ false           ┆ false               ┆ 103.878014  ┆ 100.520325      ┆ 0.041096       ┆ 0.025003     ┆ 12         ┆ 1226         │
│ 109       ┆ 1            ┆ lookback__5m__u2 ┆ 24            ┆ 0.2 ┆ 0.6 ┆ false           ┆ false               ┆ 103.741302  ┆ 100.529663      ┆ 0.041325       ┆ 0.026892     ┆ 12         ┆ 1190         │
└───────────┴──────────────┴──────────────────┴───────────────┴─────┴─────┴─────────────────┴─────────────────────┴─────────────┴─────────────────┴────────────────┴──────────────┴────────────┴──────────────┘

In [5]:
# --- Configuration ---
TARGET_REGIME_ID = 92

# Ensure we can see the full string for signal_scope_id
pl.Config.set_fmt_str_lengths(200) 

# 1. Filter for the specific regime and aggregate
regime_summary = (
    df_master
    .filter(pl.col("regime_id") == TARGET_REGIME_ID)
    .group_by("regime_id")
    .agg([
        # Parameters (taking first since they are identical across eras for one regime)
        pl.col("signal_scope_id").first(),
        pl.col("signal_layer").first(),
        pl.col("exit_window_h").first(),
        pl.col("SL").first(),
        pl.col("TP").first(),
        pl.col("use_trailing_sl").first(),
        pl.col("trade_overlap").first(),
        pl.col("trade_flip_on_entry").first(),
        
        # Results (Aggregating across all eras)
        pl.col("era_int").n_unique().alias("total_eras_sampled"),
        pl.col("balance").mean().alias("avg_balance"),
        pl.col("balance").min().alias("worst_era_balance"),
        pl.col("max_drawdown").max().alias("max_drawdown_peak"),
        pl.col("total_pos").sum().alias("total_trades_all_eras"),
        
        # The full JSON if you need to inspect it
        pl.col("signal_json").first()
    ])
)

# 2. Print full signal_scope_id separately for clarity
if not regime_summary.is_empty():
    full_scope_id = regime_summary["signal_scope_id"]
    print(f"--- Full Analysis for Regime ID: {TARGET_REGIME_ID} ---")
    print(f"Full signal_scope_id: {full_scope_id}")
    print("-" * 50)
    print(regime_summary)
else:
    print(f"Regime ID {TARGET_REGIME_ID} not found in the dataset.")

--- Full Analysis for Regime ID: 92 ---
Full signal_scope_id: shape: (1,)
Series: 'signal_scope_id' [str]
[
	"stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u2"
]
--------------------------------------------------
shape: (1, 15)
┌───────────┬──────────────────────────────────────────────────────┬──────────────┬───────────────┬─────┬─────┬─────────────────┬───────────────┬─────────────────────┬────────────────────┬─────────────┬───────────────────┬───────────────────┬───────────────────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ regime_id ┆ signal_scope_id                                      ┆ signal_layer ┆ exit_window_h ┆ SL  ┆ TP  ┆ use_trailing_sl ┆ trade_overlap ┆ trade_flip_on_entry ┆ total_eras_sampled ┆ avg_balance ┆ worst_era_balance ┆ max_drawdown_peak ┆ total_trades_all_eras ┆ signal_json                                                                                                                                                                                               │
│ ---       ┆ ---                                                  ┆ ---          ┆ ---           ┆ --- ┆ --- ┆ ---             ┆ ---           ┆ ---                 ┆ ---                ┆ ---         ┆ ---               ┆ ---               ┆ ---                   ┆ ---                                                                                                                                                                                                       │
│ i32       ┆ str                                                  ┆ i8           ┆ i32           ┆ f32 ┆ f32 ┆ bool            ┆ bool          ┆ bool                ┆ u32                ┆ f32         ┆ f32               ┆ f32               ┆ i32                   ┆ str                                                                                                                                                                                                       │
╞═══════════╪══════════════════════════════════════════════════════╪══════════════╪═══════════════╪═════╪═════╪═════════════════╪═══════════════╪═════════════════════╪════════════════════╪═════════════╪═══════════════════╪═══════════════════╪═══════════════════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╡
│ 92        ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u2 ┆ 2            ┆ 2             ┆ 0.2 ┆ 0.6 ┆ false           ┆ false         ┆ false               ┆ 12                 ┆ 102.813812  ┆ 97.332436         ┆ 0.048992          ┆ 1154                  ┆ {"signals":{"lookback":{"5m":{"entry_lookback_units":[2],"timeframe":"5m"}},"stochastic":{"15m":{"d":[8],"k":[12],"s":[4],"threshold_tolerance":10.0,"thresholds":[[30.0,70.0]],"timeframe":"15m"}}},"ve… │
└───────────┴──────────────────────────────────────────────────────┴──────────────┴───────────────┴─────┴─────┴─────────────────┴───────────────┴─────────────────────┴────────────────────┴─────────────┴───────────────────┴───────────────────┴───────────────────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [4]:
# --- Baseline verification cell ---

# Heuristic definition of "baseline":
# 1) empty signal_scope_id OR
# 2) signal_scope_id contains 'baseline'
baseline_df = df_master.filter(
    (pl.col("signal_scope_id").is_null()) |
    (pl.col("signal_scope_id") == "") |
    (pl.col("signal_scope_id").str.contains("baseline", literal=False))
)

print("Baseline rows:", baseline_df.height)

if baseline_df.height == 0:
    print("❌ No baseline signal found at all")
else:
    print("✅ Baseline signal exists")

    # Basic sanity stats
    baseline_summary = (
        baseline_df
        .select([
            pl.col("era_int").n_unique().alias("eras"),
            pl.col("regime_id").n_unique().alias("regimes"),
            pl.col("balance").min().alias("min_balance"),
            pl.col("balance").max().alias("max_balance"),
            pl.col("balance").mean().alias("mean_balance"),
        ])
    )
    print("\nBaseline summary:")
    display(baseline_summary)

    # Check if baseline ever beats starting equity
    profitable_baseline = baseline_df.filter(pl.col("balance") > 100.0)

    print("\nBaseline rows with balance > 100:", profitable_baseline.height)

    if profitable_baseline.height == 0:
        print("❌ Baseline never exceeds 100 balance")
    else:
        print("✅ Baseline produces equity growth")

        # Show best baseline rows
        display(
            profitable_baseline
            .sort("balance", descending=True)
            .select([
                "era_int",
                "regime_id",
                "signal_scope_id",
                "SL",
                "TP",
                "total_pos",
                "win_pos",
                "balance",
                "max_drawdown",
            ])
            .head(20)
        )

Baseline rows: 3600
✅ Baseline signal exists

Baseline summary:

shape: (1, 5)
┌──────┬─────────┬─────────────┬─────────────┬──────────────┐
│ eras ┆ regimes ┆ min_balance ┆ max_balance ┆ mean_balance │
│ ---  ┆ ---     ┆ ---         ┆ ---         ┆ ---          │
│ u32  ┆ u32     ┆ f32         ┆ f32         ┆ f32          │
╞══════╪═════════╪═════════════╪═════════════╪══════════════╡
│ 12   ┆ 300     ┆ 89.468056   ┆ 123.09539   ┆ 100.327591   │
└──────┴─────────┴─────────────┴─────────────┴──────────────┘

Baseline rows with balance > 100: 1832
✅ Baseline produces equity growth

shape: (20, 9)
┌──────────┬───────────┬───────────────────┬─────┬─────┬───────────┬─────────┬────────────┬──────────────┐
│ era_int  ┆ regime_id ┆ signal_scope_id   ┆ SL  ┆ TP  ┆ total_pos ┆ win_pos ┆ balance    ┆ max_drawdown │
│ ---      ┆ ---       ┆ ---               ┆ --- ┆ --- ┆ ---       ┆ ---     ┆ ---        ┆ ---          │
│ i64      ┆ i32       ┆ str               ┆ f32 ┆ f32 ┆ i32       ┆ i32     ┆ f32        ┆ f32          │
╞══════════╪═══════════╪═══════════════════╪═════╪═════╪═══════════╪═════════╪════════════╪══════════════╡
│ 20241201 ┆ 561       ┆ baseline:all_buy  ┆ 0.6 ┆ 0.8 ┆ 92        ┆ 55      ┆ 123.09539  ┆ 0.023959     │
│ 20241201 ┆ 563       ┆ baseline:all_sell ┆ 0.6 ┆ 0.8 ┆ 92        ┆ 55      ┆ 123.09539  ┆ 0.023959     │
│ 20241201 ┆ 813       ┆ baseline:all_buy  ┆ 0.8 ┆ 1.0 ┆ 82        ┆ 48      ┆ 121.893219 ┆ 0.047847     │
│ 20241201 ┆ 815       ┆ baseline:all_sell ┆ 0.8 ┆ 1.0 ┆ 82        ┆ 48      ┆ 121.893219 ┆ 0.047847     │
│ 20241201 ┆ 910       ┆ baseline:all_buy  ┆ 1.0 ┆ 0.4 ┆ 93        ┆ 78      ┆ 120.495064 ┆ 0.023152     │
│ 20241201 ┆ 912       ┆ baseline:all_sell ┆ 1.0 ┆ 0.4 ┆ 93        ┆ 78      ┆ 120.495064 ┆ 0.023152     │
│ 20241201 ┆ 981       ┆ baseline:all_buy  ┆ 1.0 ┆ 0.8 ┆ 85        ┆ 58      ┆ 120.230873 ┆ 0.041408     │
│ 20241201 ┆ 983       ┆ baseline:all_sell ┆ 1.0 ┆ 0.8 ┆ 85        ┆ 58      ┆ 120.230873 ┆ 0.041408     │
│ 20231201 ┆ 1023      ┆ baseline:all_buy  ┆ 1.0 ┆ 1.0 ┆ 82        ┆ 50      ┆ 119.780968 ┆ 0.063808     │
│ 20231201 ┆ 1025      ┆ baseline:all_sell ┆ 1.0 ┆ 1.0 ┆ 82        ┆ 50      ┆ 119.780968 ┆ 0.063808     │
│ 20241201 ┆ 771       ┆ baseline:all_buy  ┆ 0.8 ┆ 0.8 ┆ 88        ┆ 56      ┆ 119.520996 ┆ 0.031941     │
│ 20241201 ┆ 773       ┆ baseline:all_sell ┆ 0.8 ┆ 0.8 ┆ 88        ┆ 56      ┆ 119.520996 ┆ 0.031941     │
│ 20250301 ┆ 392       ┆ baseline:all_buy  ┆ 0.4 ┆ 1.0 ┆ 84        ┆ 37      ┆ 119.050835 ┆ 0.025793     │
│ 20250301 ┆ 394       ┆ baseline:all_sell ┆ 0.4 ┆ 1.0 ┆ 84        ┆ 37      ┆ 119.050835 ┆ 0.025793     │
│ 20230301 ┆ 602       ┆ baseline:all_buy  ┆ 0.6 ┆ 1.0 ┆ 80        ┆ 41      ┆ 118.383614 ┆ 0.039491     │
│ 20230301 ┆ 604       ┆ baseline:all_sell ┆ 0.6 ┆ 1.0 ┆ 80        ┆ 41      ┆ 118.383614 ┆ 0.039491     │
│ 20221201 ┆ 533       ┆ baseline:all_buy  ┆ 0.6 ┆ 0.6 ┆ 95        ┆ 62      ┆ 115.734413 ┆ 0.032252     │
│ 20221201 ┆ 535       ┆ baseline:all_sell ┆ 0.6 ┆ 0.6 ┆ 95        ┆ 62      ┆ 115.734413 ┆ 0.032252     │
│ 20240901 ┆ 771       ┆ baseline:all_buy  ┆ 0.8 ┆ 0.8 ┆ 84        ┆ 51      ┆ 115.678131 ┆ 0.05756      │
│ 20240901 ┆ 773       ┆ baseline:all_sell ┆ 0.8 ┆ 0.8 ┆ 84        ┆ 51      ┆ 115.678131 ┆ 0.05756      │
└──────────┴───────────┴───────────────────┴─────┴─────┴───────────┴─────────┴────────────┴──────────────┘

In [10]:
from pathlib import Path
import polars as pl

session_dir = Path(r"C:\Users\Owner\airflow-trading\data_lake\Opt_Session_20260426_092617_01")
regime_id = 92

master_path = session_dir / "master_metrics.parquet"
df_master = pl.read_parquet(master_path)

trade_ml_root = session_dir / "trade_ml_partitioned"
trade_paths = sorted(trade_ml_root.glob("era_int=*/trade_ml_era_int=*.parquet"))

df_trade = pl.concat([pl.read_parquet(str(p)) for p in trade_paths], how="vertical") if trade_paths else pl.DataFrame()

print("MASTER rows for regime", regime_id)
print(
    df_master
    .filter(pl.col("regime_id") == regime_id)
    .select(["regime_id", "signal_layer", "signal_scope_id", "era_int", "SL", "TP", "total_pos", "win_pos", "balance", "max_drawdown", "max_consecutive_losses"])
    .sort(["era_int", "SL", "TP"])
)

print("\nTRADE_ML rows for regime", regime_id)
if df_trade.is_empty():
    print("trade_ml is empty")
else:
    print(
        df_trade
        .filter(pl.col("regime_id") == regime_id)
        .select(["regime_id", "signal_layer", "signal_scope_id", "era_int", "SL", "TP", "signal_idx", "entry_idx", "exit_idx", "pnl_pct"])
        .sort(["era_int", "SL", "TP"])
    )

print("\nDoes regime exist in trade_ml?", not df_trade.filter(pl.col("regime_id") == regime_id).is_empty())

MASTER rows for regime 92
shape: (300, 11)
┌───────────┬──────────────┬──────────────────────────────────────────────────────┬──────────┬─────┬─────┬───────────┬─────────┬────────────┬──────────────┬────────────────────────┐
│ regime_id ┆ signal_layer ┆ signal_scope_id                                      ┆ era_int  ┆ SL  ┆ TP  ┆ total_pos ┆ win_pos ┆ balance    ┆ max_drawdown ┆ max_consecutive_losses │
│ ---       ┆ ---          ┆ ---                                                  ┆ ---      ┆ --- ┆ --- ┆ ---       ┆ ---     ┆ ---        ┆ ---          ┆ ---                    │
│ i32       ┆ i8           ┆ str                                                  ┆ i64      ┆ f32 ┆ f32 ┆ i32       ┆ i32     ┆ f32        ┆ f32          ┆ i32                    │
╞═══════════╪══════════════╪══════════════════════════════════════════════════════╪══════════╪═════╪═════╪═══════════╪═════════╪════════════╪══════════════╪════════════════════════╡
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.2 ┆ 0.2 ┆ 99        ┆ 53      ┆ 101.379738 ┆ 0.017924     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.2 ┆ 0.4 ┆ 95        ┆ 35      ┆ 101.969711 ┆ 0.01986      ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.2 ┆ 0.6 ┆ 92        ┆ 22      ┆ 99.141052  ┆ 0.029625     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.2 ┆ 0.8 ┆ 89        ┆ 15      ┆ 97.169365  ┆ 0.043667     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.2 ┆ 1.0 ┆ 87        ┆ 13      ┆ 98.129623  ┆ 0.031667     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.4 ┆ 0.2 ┆ 96        ┆ 69      ┆ 102.999054 ┆ 0.023826     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.4 ┆ 0.4 ┆ 90        ┆ 56      ┆ 109.110458 ┆ 0.023943     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.4 ┆ 0.6 ┆ 88        ┆ 41      ┆ 105.844406 ┆ 0.033597     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.4 ┆ 0.8 ┆ 83        ┆ 26      ┆ 97.440506  ┆ 0.047309     ┆ 7                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.4 ┆ 1.0 ┆ 83        ┆ 22      ┆ 96.830559  ┆ 0.06213      ┆ 16                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.6 ┆ 0.2 ┆ 94        ┆ 74      ┆ 102.77755  ┆ 0.037448     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.6 ┆ 0.4 ┆ 88        ┆ 54      ┆ 101.092598 ┆ 0.056811     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.6 ┆ 0.6 ┆ 82        ┆ 39      ┆ 97.476547  ┆ 0.042241     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.6 ┆ 0.8 ┆ 78        ┆ 35      ┆ 101.597565 ┆ 0.033364     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.6 ┆ 1.0 ┆ 76        ┆ 28      ┆ 98.326485  ┆ 0.050985     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.8 ┆ 0.2 ┆ 92        ┆ 77      ┆ 103.383133 ┆ 0.0239       ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.8 ┆ 0.4 ┆ 84        ┆ 60      ┆ 105.422318 ┆ 0.056855     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.8 ┆ 0.6 ┆ 81        ┆ 50      ┆ 105.129768 ┆ 0.038071     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.8 ┆ 0.8 ┆ 74        ┆ 38      ┆ 100.712761 ┆ 0.054999     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 0.8 ┆ 1.0 ┆ 70        ┆ 32      ┆ 100.659721 ┆ 0.051051     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 1.0 ┆ 0.2 ┆ 91        ┆ 81      ┆ 106.315819 ┆ 0.025821     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 1.0 ┆ 0.4 ┆ 80        ┆ 54      ┆ 95.792664  ┆ 0.067915     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 1.0 ┆ 0.6 ┆ 75        ┆ 52      ┆ 108.618401 ┆ 0.040832     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 1.0 ┆ 0.8 ┆ 70        ┆ 38      ┆ 96.427635  ┆ 0.066603     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20220901 ┆ 1.0 ┆ 1.0 ┆ 70        ┆ 37      ┆ 101.241226 ┆ 0.058976     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.2 ┆ 0.2 ┆ 96        ┆ 59      ┆ 104.468155 ┆ 0.009995     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.2 ┆ 0.4 ┆ 89        ┆ 38      ┆ 105.075157 ┆ 0.015896     ┆ 8                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.2 ┆ 0.6 ┆ 86        ┆ 20      ┆ 98.293884  ┆ 0.037396     ┆ 16                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.2 ┆ 0.8 ┆ 82        ┆ 16      ┆ 99.062927  ┆ 0.039311     ┆ 13                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.2 ┆ 1.0 ┆ 81        ┆ 15      ┆ 100.847763 ┆ 0.037405     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.4 ┆ 0.2 ┆ 90        ┆ 59      ┆ 99.35643   ┆ 0.03551      ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.4 ┆ 0.4 ┆ 81        ┆ 48      ┆ 105.940788 ┆ 0.024031     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.4 ┆ 0.6 ┆ 76        ┆ 32      ┆ 101.041969 ┆ 0.056565     ┆ 8                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.4 ┆ 0.8 ┆ 76        ┆ 25      ┆ 99.078712  ┆ 0.06981      ┆ 10                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.4 ┆ 1.0 ┆ 74        ┆ 21      ┆ 98.463127  ┆ 0.058777     ┆ 9                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.6 ┆ 0.2 ┆ 87        ┆ 69      ┆ 102.988785 ┆ 0.033623     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.6 ┆ 0.4 ┆ 78        ┆ 59      ┆ 112.510567 ┆ 0.03547      ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.6 ┆ 0.6 ┆ 72        ┆ 37      ┆ 99.679741  ┆ 0.050912     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.6 ┆ 0.8 ┆ 71        ┆ 32      ┆ 100.040756 ┆ 0.060369     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20221201 ┆ 0.6 ┆ 1.0 ┆ 69        ┆ 28      ┆ 101.672928 ┆ 0.054242     ┆ 7                      │
│ …         ┆ …            ┆ …                                                    ┆ …        ┆ …   ┆ …   ┆ …         ┆ …       ┆ …          ┆ …            ┆ …                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.6 ┆ 0.2 ┆ 95        ┆ 73      ┆ 101.345131 ┆ 0.024227     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.6 ┆ 0.4 ┆ 91        ┆ 56      ┆ 101.291229 ┆ 0.045698     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.6 ┆ 0.6 ┆ 85        ┆ 41      ┆ 98.057587  ┆ 0.058809     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.6 ┆ 0.8 ┆ 81        ┆ 41      ┆ 107.911354 ┆ 0.027925     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.6 ┆ 1.0 ┆ 78        ┆ 25      ┆ 92.62606   ┆ 0.084597     ┆ 7                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.8 ┆ 0.2 ┆ 91        ┆ 70      ┆ 97.150734  ┆ 0.041503     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.8 ┆ 0.4 ┆ 86        ┆ 59      ┆ 101.874825 ┆ 0.051046     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.8 ┆ 0.6 ┆ 80        ┆ 50      ┆ 105.5812   ┆ 0.067999     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.8 ┆ 0.8 ┆ 76        ┆ 45      ┆ 110.334732 ┆ 0.05493      ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 0.8 ┆ 1.0 ┆ 72        ┆ 32      ┆ 100.196617 ┆ 0.067963     ┆ 7                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 1.0 ┆ 0.2 ┆ 89        ┆ 70      ┆ 95.010262  ┆ 0.064956     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 1.0 ┆ 0.4 ┆ 83        ┆ 62      ┆ 104.107613 ┆ 0.043516     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 1.0 ┆ 0.6 ┆ 78        ┆ 58      ┆ 115.705223 ┆ 0.03573      ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 1.0 ┆ 0.8 ┆ 73        ┆ 49      ┆ 114.103027 ┆ 0.060486     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250301 ┆ 1.0 ┆ 1.0 ┆ 72        ┆ 36      ┆ 99.505379  ┆ 0.086595     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.2 ┆ 0.2 ┆ 97        ┆ 42      ┆ 97.405151  ┆ 0.045087     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.2 ┆ 0.4 ┆ 94        ┆ 32      ┆ 99.967102  ┆ 0.027565     ┆ 12                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.2 ┆ 0.6 ┆ 89        ┆ 27      ┆ 103.394783 ┆ 0.023773     ┆ 9                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.2 ┆ 0.8 ┆ 86        ┆ 14      ┆ 96.185516  ┆ 0.057008     ┆ 11                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.2 ┆ 1.0 ┆ 81        ┆ 11      ┆ 96.733765  ┆ 0.057278     ┆ 16                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.4 ┆ 0.2 ┆ 91        ┆ 57      ┆ 97.777313  ┆ 0.037709     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.4 ┆ 0.4 ┆ 86        ┆ 39      ┆ 96.403297  ┆ 0.062476     ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.4 ┆ 0.6 ┆ 82        ┆ 33      ┆ 100.487587 ┆ 0.049094     ┆ 9                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.4 ┆ 0.8 ┆ 76        ┆ 22      ┆ 94.704041  ┆ 0.06593      ┆ 17                     │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.4 ┆ 1.0 ┆ 72        ┆ 21      ┆ 99.501488  ┆ 0.047454     ┆ 8                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.6 ┆ 0.2 ┆ 89        ┆ 67      ┆ 100.138054 ┆ 0.031637     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.6 ┆ 0.4 ┆ 83        ┆ 47      ┆ 96.757317  ┆ 0.054891     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.6 ┆ 0.6 ┆ 74        ┆ 37      ┆ 98.513527  ┆ 0.056395     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.6 ┆ 0.8 ┆ 70        ┆ 34      ┆ 103.914162 ┆ 0.03547      ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.6 ┆ 1.0 ┆ 68        ┆ 32      ┆ 107.520271 ┆ 0.047012     ┆ 8                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.8 ┆ 0.2 ┆ 88        ┆ 65      ┆ 94.652504  ┆ 0.073957     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.8 ┆ 0.4 ┆ 79        ┆ 55      ┆ 102.311768 ┆ 0.043392     ┆ 4                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.8 ┆ 0.6 ┆ 69        ┆ 38      ┆ 97.094986  ┆ 0.068761     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.8 ┆ 0.8 ┆ 64        ┆ 34      ┆ 102.001228 ┆ 0.06099      ┆ 6                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 0.8 ┆ 1.0 ┆ 61        ┆ 31      ┆ 105.378815 ┆ 0.049738     ┆ 5                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 1.0 ┆ 0.2 ┆ 84        ┆ 67      ┆ 97.119942  ┆ 0.041579     ┆ 2                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 1.0 ┆ 0.4 ┆ 74        ┆ 51      ┆ 97.920334  ┆ 0.051121     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 1.0 ┆ 0.6 ┆ 64        ┆ 44      ┆ 105.0      ┆ 0.034018     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 1.0 ┆ 0.8 ┆ 59        ┆ 36      ┆ 106.548241 ┆ 0.027518     ┆ 3                      │
│ 92        ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 20250601 ┆ 1.0 ┆ 1.0 ┆ 58        ┆ 32      ┆ 104.828804 ┆ 0.059718     ┆ 4                      │
└───────────┴──────────────┴──────────────────────────────────────────────────────┴──────────┴─────┴─────┴───────────┴─────────┴────────────┴──────────────┴────────────────────────┘

TRADE_ML rows for regime 92
shape: (0, 10)
┌───────────┬──────────────┬─────────────────┬─────────┬─────┬─────┬────────────┬───────────┬──────────┬─────────┐
│ regime_id ┆ signal_layer ┆ signal_scope_id ┆ era_int ┆ SL  ┆ TP  ┆ signal_idx ┆ entry_idx ┆ exit_idx ┆ pnl_pct │
│ ---       ┆ ---          ┆ ---             ┆ ---     ┆ --- ┆ --- ┆ ---        ┆ ---       ┆ ---      ┆ ---     │
│ i32       ┆ i8           ┆ str             ┆ i64     ┆ f32 ┆ f32 ┆ i64        ┆ i64       ┆ i64      ┆ f32     │
╞═══════════╪══════════════╪═════════════════╪═════════╪═════╪═════╪════════════╪═══════════╪══════════╪═════════╡
└───────────┴──────────────┴─────────────────┴─────────┴─────┴─────┴────────────┴───────────┴──────────┴─────────┘

Does regime exist in trade_ml? False

In [11]:
from pathlib import Path
import json
import polars as pl

session_dir = Path(r"C:\Users\Owner\airflow-trading\data_lake\Opt_Session_20260426_092617_01")
cfg_dir = session_dir / "configs"

rows = []
for p in sorted(cfg_dir.glob("batch_*.json")):
    with open(p, "r", encoding="utf8") as f:
        batch = json.load(f)
    for r in batch.get("regimes", []):
        if int(r.get("regime_id", -1)) == 92:
            rows.append({
                "batch": p.name,
                "regime_id": r.get("regime_id"),
                "regime_key": r.get("regime_key"),
                "signal_layer": r.get("signal_layer"),
                "signal_scope_id": r.get("signal_scope_id"),
                "SL": r.get("SL"),
                "TP": r.get("TP"),
            })

df = pl.DataFrame(rows) if rows else pl.DataFrame(schema={
    "batch": pl.Utf8,
    "regime_id": pl.Int64,
    "regime_key": pl.Utf8,
    "signal_layer": pl.Int64,
    "signal_scope_id": pl.Utf8,
    "SL": pl.Float64,
    "TP": pl.Float64,
})

print("Current config entries for regime_id 92:")
print(df)

if df.is_empty():
    print("\nRegime 92 is not present in the current configs, so the master row is stale/mixed from an older run.")

Current config entries for regime_id 92:
shape: (1, 7)
┌─────────────────┬───────────┬───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────┬──────────────────────────────────────────────────────┬─────┬─────┐
│ batch           ┆ regime_id ┆ regime_key                                                                                                                                                                                                ┆ signal_layer ┆ signal_scope_id                                      ┆ SL  ┆ TP  │
│ ---             ┆ ---       ┆ ---                                                                                                                                                                                                       ┆ ---          ┆ ---                                                  ┆ --- ┆ --- │
│ str             ┆ i64       ┆ str                                                                                                                                                                                                       ┆ i64          ┆ str                                                  ┆ f64 ┆ f64 │
╞═════════════════╪═══════════╪═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════╪══════════════════════════════════════════════════════╪═════╪═════╡
│ batch_0000.json ┆ 92        ┆ {"SL":0.20000000298023224,"TP":0.20000000298023224,"exit_window_h":24,"limit_order_expiry_bars":3,"signal_json":"{\"signals\":{\"lookback\":{\"5m\":{\"entry_lookback_units\":[1],\"timeframe\":\"5m\"}}… ┆ 2            ┆ stoch__15m__k12_d8_s4_l30_u70_tol10|lookback__5m__u1 ┆ 0.2 ┆ 0.2 │
└─────────────────┴───────────┴───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────┴──────────────────────────────────────────────────────┴─────┴─────┘

In [12]:
from pathlib import Path
import json
import polars as pl

session_dir = Path(r"C:\Users\Owner\airflow-trading\data_lake\Opt_Session_20260426_092617_01")
cfg_dir = session_dir / "configs"

rows = []
for p in sorted(cfg_dir.glob("batch_*.json")):
    with open(p, "r", encoding="utf8") as f:
        batch = json.load(f)
    for r in batch.get("regimes", []):
        rows.append({
            "batch": p.name,
            "regime_id": r.get("regime_id"),
            "regime_key": r.get("regime_key"),
            "signal_layer": r.get("signal_layer"),
            "signal_scope_id": r.get("signal_scope_id"),
        })

df_cfg = pl.DataFrame(rows)

dup_keys = (
    df_cfg
    .group_by("regime_key")
    .agg(
        pl.col("regime_id").n_unique().alias("regime_id_count"),
        pl.col("regime_id").unique().alias("regime_ids"),
        pl.col("batch").n_unique().alias("batch_count"),
        pl.col("batch").unique().alias("batches"),
        pl.col("signal_layer").first().alias("signal_layer"),
        pl.col("signal_scope_id").first().alias("signal_scope_id"),
    )
    .filter(pl.col("regime_id_count") > 1)
    .sort("regime_id_count", descending=True)
)

print("Duplicate regime_key mappings:", dup_keys.height)
print(dup_keys.head(20))

Duplicate regime_key mappings: 0
shape: (0, 7)
┌────────────┬─────────────────┬────────────┬─────────────┬───────────┬──────────────┬─────────────────┐
│ regime_key ┆ regime_id_count ┆ regime_ids ┆ batch_count ┆ batches   ┆ signal_layer ┆ signal_scope_id │
│ ---        ┆ ---             ┆ ---        ┆ ---         ┆ ---       ┆ ---          ┆ ---             │
│ str        ┆ u32             ┆ list[i64]  ┆ u32         ┆ list[str] ┆ i64          ┆ str             │
╞════════════╪═════════════════╪════════════╪═════════════╪═══════════╪══════════════╪═════════════════╡
└────────────┴─────────────────┴────────────┴─────────────┴───────────┴──────────────┴─────────────────┘

In [2]:
# Map era -> volatility

amp_data = [
    {
        "era_int": 20220901,
        "window_start_time": "2022-09-01 00:00:00+00:00",
        "window_end_time": "2022-12-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26208,
        "window_min_close": 15593.58,
        "window_max_close": 22713.69,
        "regime_amp_index": 0.456605
    },
    {
        "era_int": 20221201,
        "window_start_time": "2022-12-01 00:00:00+00:00",
        "window_end_time": "2023-03-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 25920,
        "window_min_close": 16366.60,
        "window_max_close": 25235.36,
        "regime_amp_index": 0.541882
    },
    {
        "era_int": 20230301,
        "window_start_time": "2023-03-01 00:00:00+00:00",
        "window_end_time": "2023-06-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 19611.25,
        "window_max_close": 30963.13,
        "regime_amp_index": 0.578845
    },
    {
        "era_int": 20230601,
        "window_start_time": "2023-06-01 00:00:00+00:00",
        "window_end_time": "2023-09-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 24891.49,
        "window_max_close": 31710.95,
        "regime_amp_index": 0.273968
    },
    {
        "era_int": 20230901,
        "window_start_time": "2023-09-01 00:00:00+00:00",
        "window_end_time": "2023-12-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26208,
        "window_min_close": 25003.56,
        "window_max_close": 38383.09,
        "regime_amp_index": 0.535105
    },
    {
        "era_int": 20231201,
        "window_start_time": "2023-12-01 00:00:00+00:00",
        "window_end_time": "2024-03-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26208,
        "window_min_close": 37627.91,
        "window_max_close": 63690.12,
        "regime_amp_index": 0.692630
    },
    {
        "era_int": 20240301,
        "window_start_time": "2024-03-01 00:00:00+00:00",
        "window_end_time": "2024-06-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 56773.99,
        "window_max_close": 73628.42,
        "regime_amp_index": 0.296869
    },
    {
        "era_int": 20240601,
        "window_start_time": "2024-06-01 00:00:00+00:00",
        "window_end_time": "2024-09-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 49338.49,
        "window_max_close": 71956.73,
        "regime_amp_index": 0.458430
    },
    {
        "era_int": 20240901,
        "window_start_time": "2024-09-01 00:00:00+00:00",
        "window_end_time": "2024-12-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26208,
        "window_min_close": 52738.00,
        "window_max_close": 99521.87,
        "regime_amp_index": 0.887100
    },
    {
        "era_int": 20241201,
        "window_start_time": "2024-12-01 00:00:00+00:00",
        "window_end_time": "2025-03-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 25920,
        "window_min_close": 78487.01,
        "window_max_close": 108984.96,
        "regime_amp_index": 0.388573
    },
    {
        "era_int": 20250301,
        "window_start_time": "2025-03-01 00:00:00+00:00",
        "window_end_time": "2025-06-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 74610.00,
        "window_max_close": 111924.08,
        "regime_amp_index": 0.500122
    },
    {
        "era_int": 20250601,
        "window_start_time": "2025-06-01 00:00:00+00:00",
        "window_end_time": "2025-09-01 00:00:00+00:00",
        "timeframe_months": 3,
        "window_rows": 26496,
        "window_min_close": 98392.91,
        "window_max_close": 124243.32,
        "regime_amp_index": 0.262726
    },
    {
        "era_int": 20250901,
        "window_start_time": "2025-09-01 00:00:00+00:00",
        "window_end_time": "2025-09-15 23:59:59+00:00",
        "timeframe_months": 3,
        "window_rows": 4320,
        "window_min_close": 107303.99,
        "window_max_close": 116745.67,
        "regime_amp_index": 0.087990
    }
]
import polars as pl

# 1. Convert your list of dictionaries into a Polars DataFrame
# We only select 'era_int' and 'regime_amp_index' as those are the keys for correlation
amp_df = (
    pl.DataFrame(amp_data)
    .select([
        pl.col("era_int"),
        pl.col("regime_amp_index").alias("regime_amp")  # Rename to match your analysis script
    ])
    .with_columns(pl.col("era_int").cast(pl.Int64)) # Ensure data types match for the join
)

# 2. Link the Volatility data to your Master Backtest data
# This is the 'bridge' that allows you to calculate correlation
df_analysis = (
    df_master
    .with_columns(pl.col("era_int").cast(pl.Int64)) # Ensure join key types are identical
    .join(amp_df, on="era_int", how="left")        # Map volatility to every single trade result
    .filter(pl.col("total_pos") >= 30)             # Apply trade floor for significance
    .with_columns([
        # Volatility-Adjusted Alpha Calculation
        ((((pl.col("balance") - 100) / 100) / (pl.col("total_pos") + 1e-9)) / 
         (pl.col("max_drawdown").clip(0.001))).alias("alpha_per_trade"),
        
        # Total Trade Space (TP + SL)
        (pl.col("TP") + pl.col("SL")).alias("total_spread")
    ])
)

# 3. Aggregate to find the "Best" parameters for every Volatility level
regime_winners = (
    df_analysis
    .group_by(["regime_amp", "TP", "SL", "total_spread"])
    .agg(pl.col("alpha_per_trade").median().alias("median_alpha"))
    .sort(["regime_amp", "median_alpha"], descending=[False, True])
    .group_by("regime_amp")
    .head(1)
    .sort("regime_amp")
)

# 4. Final Spearman Rho Check
correlations = regime_winners.select([
    pl.corr("regime_amp", "TP", method="spearman").alias("rho_vol_vs_TP"),
    pl.corr("regime_amp", "SL", method="spearman").alias("rho_vol_vs_SL"),
    pl.corr("regime_amp", "total_spread", method="spearman").alias("rho_vol_vs_TotalSpread")
])

print("--- IDEAL PARAMETERS PER VOLATILITY REGIME ---")
print(regime_winners.select(["regime_amp", "TP", "SL", "total_spread", "median_alpha"]))

print("\n--- GLOBAL CORRELATION RESULTS ---")
print(correlations)

--- IDEAL PARAMETERS PER VOLATILITY REGIME ---
shape: (12, 5)
┌────────────┬─────┬─────┬──────────────┬──────────────┐
│ regime_amp ┆ TP  ┆ SL  ┆ total_spread ┆ median_alpha │
│ ---        ┆ --- ┆ --- ┆ ---          ┆ ---          │
│ f64        ┆ f32 ┆ f32 ┆ f32          ┆ f32          │
╞════════════╪═════╪═════╪══════════════╪══════════════╡
│ 0.262726   ┆ 4.5 ┆ 0.4 ┆ 4.9          ┆ -0.000641    │
│ 0.273968   ┆ 3.0 ┆ 0.2 ┆ 3.2          ┆ 0.002647     │
│ 0.296869   ┆ 6.0 ┆ 0.4 ┆ 6.4          ┆ 0.015605     │
│ 0.388573   ┆ 5.5 ┆ 0.2 ┆ 5.7          ┆ 0.022873     │
│ 0.456605   ┆ 4.0 ┆ 0.2 ┆ 4.2          ┆ 0.028315     │
│ 0.45843    ┆ 3.0 ┆ 0.2 ┆ 3.2          ┆ 0.066889     │
│ 0.500122   ┆ 2.0 ┆ 0.4 ┆ 2.4          ┆ 0.019333     │
│ 0.535105   ┆ 2.0 ┆ 0.2 ┆ 2.2          ┆ 0.00779      │
│ 0.541882   ┆ 2.0 ┆ 0.4 ┆ 2.4          ┆ -0.000527    │
│ 0.578845   ┆ 4.0 ┆ 0.4 ┆ 4.4          ┆ 0.00204      │
│ 0.69263    ┆ 4.5 ┆ 0.4 ┆ 4.9          ┆ 0.009275     │
│ 0.8871     ┆ 2.5 ┆ 0.4 ┆ 2.9          ┆ 0.012208     │
└────────────┴─────┴─────┴──────────────┴──────────────┘

--- GLOBAL CORRELATION RESULTS ---
shape: (1, 3)
┌───────────────┬───────────────┬────────────────────────┐
│ rho_vol_vs_TP ┆ rho_vol_vs_SL ┆ rho_vol_vs_TotalSpread │
│ ---           ┆ ---           ┆ ---                    │
│ f64           ┆ f64           ┆ f64                    │
╞═══════════════╪═══════════════╪════════════════════════╡
│ -0.428351     ┆ 0.36724       ┆ -0.407739              │
└───────────────┴───────────────┴────────────────────────┘

In [ ]:
from feature_perf import feature_performance

results_stoch_15m = feature_performance(df_master, "stoch_key (15m)")
results_tp = feature_performance(df_master, "lookback_key (5m)")
results_tp = feature_performance(df_master, "lookback_key (15m)")

results_exit = feature_performance(df_master, "exit_window_h")
results_limit = feature_performance(df_master, "trailing_sl_pct")
results_limit_ex = feature_performance(df_master, "limit_order_expiry_bars")
results_interval = feature_performance(df_master, "trade_window_interval")

--- STOCH_KEY (15M) PERFORMANCE BY ERA (FLOOR: 40) ---
shape: (12, 8)
┌──────────┬───────────────────┬────────────────┬──────────┬──────────────┬───────────────┬─────────────────────────┬─────────────────┐
│ era_int  ┆ stoch_key (15m)   ┆ median_balance ┆ avg_dd   ┆ avg_win_rate ┆ avg_total_pos ┆ median_return_per_trade ┆ alpha_per_trade │
│ ---      ┆ ---               ┆ ---            ┆ ---      ┆ ---          ┆ ---           ┆ ---                     ┆ ---             │
│ i64      ┆ str               ┆ f32            ┆ f32      ┆ f64          ┆ f64           ┆ f64                     ┆ f64             │
╞══════════╪═══════════════════╪════════════════╪══════════╪══════════════╪═══════════════╪═════════════════════════╪═════════════════╡
│ 20220901 ┆ k12_d8_s4_l30_u70 ┆ 93.705788      ┆ 0.080797 ┆ 0.30434      ┆ 63.828103     ┆ -0.000986               ┆ -0.012193       │
│ 20221201 ┆ k12_d8_s4_l30_u70 ┆ 89.881866      ┆ 0.098546 ┆ 0.31577      ┆ 59.863515     ┆ -0.00169                ┆ -0.017122       │
│ 20230301 ┆ k12_d8_s4_l30_u70 ┆ 91.003906      ┆ 0.083962 ┆ 0.303813     ┆ 61.323164     ┆ -0.001467               ┆ -0.017446       │
│ 20230601 ┆ k12_d8_s4_l30_u70 ┆ 97.810516      ┆ 0.08051  ┆ 0.30398      ┆ 64.843071     ┆ -0.000338               ┆ -0.004193       │
│ 20230901 ┆ k12_d8_s4_l30_u70 ┆ 91.035179      ┆ 0.087357 ┆ 0.29472      ┆ 64.568507     ┆ -0.001388               ┆ -0.015872       │
│ 20231201 ┆ k12_d8_s4_l30_u70 ┆ 95.195869      ┆ 0.078706 ┆ 0.289214     ┆ 65.549521     ┆ -0.000733               ┆ -0.009305       │
│ 20240301 ┆ k12_d8_s4_l30_u70 ┆ 91.757767      ┆ 0.087238 ┆ 0.253099     ┆ 64.444864     ┆ -0.001279               ┆ -0.014642       │
│ 20240601 ┆ k12_d8_s4_l30_u70 ┆ 89.858078      ┆ 0.099589 ┆ 0.226505     ┆ 65.426172     ┆ -0.00155                ┆ -0.015541       │
│ 20240901 ┆ k12_d8_s4_l30_u70 ┆ 92.926308      ┆ 0.088195 ┆ 0.277564     ┆ 65.408844     ┆ -0.001081               ┆ -0.012249       │
│ 20241201 ┆ k12_d8_s4_l30_u70 ┆ 97.342163      ┆ 0.089024 ┆ 0.236597     ┆ 66.472562     ┆ -0.0004                 ┆ -0.00449        │
│ 20250301 ┆ k12_d8_s4_l30_u70 ┆ 90.685143      ┆ 0.094284 ┆ 0.273642     ┆ 67.87469      ┆ -0.001372               ┆ -0.014536       │
│ 20250601 ┆ k12_d8_s4_l30_u70 ┆ 90.476761      ┆ 0.093815 ┆ 0.25751      ┆ 65.969866     ┆ -0.001444               ┆ -0.015365       │
└──────────┴───────────────────┴────────────────┴──────────┴──────────────┴───────────────┴─────────────────────────┴─────────────────┘

--- TOP ELITE PER ERA DOMINANCE: stoch_key (15m) ---
shape: (1, 14)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┬─────────────┬─────────────┐
│ stoch_key    ┆ dominance_sc ┆ elite_median ┆ elite_median ┆ elite_avg_m ┆ weighted_er ┆ recency_wei ┆ era_consist ┆ global_medi ┆ global_medi ┆ global_avg_ ┆ alpha_lift ┆ return_lift ┆ drawdown_ga │
│ (15m)        ┆ ore          ┆ _alpha       ┆ _return      ┆ ax_drawdown ┆ a_hits      ┆ ghted_era_c ┆ ency_score  ┆ an_alpha    ┆ an_return   ┆ max_drawdow ┆ ---        ┆ ---         ┆ p           │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ onsistency_ ┆ ---         ┆ ---         ┆ ---         ┆ n           ┆ f32        ┆ f32         ┆ ---         │
│ str          ┆ f64          ┆ f32          ┆ f32          ┆ f32         ┆ f64         ┆ score       ┆ f64         ┆ f32         ┆ f32         ┆ ---         ┆            ┆             ┆ f32         │
│              ┆              ┆              ┆              ┆             ┆             ┆ ---         ┆             ┆             ┆             ┆ f32         ┆            ┆             ┆             │
│              ┆              ┆              ┆              ┆             ┆             ┆ f64         ┆             ┆             ┆             ┆             ┆            ┆             ┆             │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╪═════════════╪═════════════╡
│ k12_d8_s4_l3 ┆ 1.0          ┆ 0.000705     ┆ 0.000049     ┆ 0.075454    ┆ 4.777662    ┆ 0.942184    ┆ 0.916667    ┆ -0.012497   ┆ -0.001151   ┆ 0.088818    ┆ 0.013202   ┆ 0.0012      ┆ 0.013364    │
│ 0_u70        ┆              ┆              ┆              ┆             ┆             ┆             ┆             ┆             ┆             ┆             ┆            ┆             ┆             │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┴─────────────┴─────────────┘

--- LOOKBACK_KEY (5M) PERFORMANCE BY ERA (FLOOR: 40) ---
shape: (24, 8)
┌──────────┬───────────────────┬────────────────┬──────────┬──────────────┬───────────────┬─────────────────────────┬─────────────────┐
│ era_int  ┆ lookback_key (5m) ┆ median_balance ┆ avg_dd   ┆ avg_win_rate ┆ avg_total_pos ┆ median_return_per_trade ┆ alpha_per_trade │
│ ---      ┆ ---               ┆ ---            ┆ ---      ┆ ---          ┆ ---           ┆ ---                     ┆ ---             │
│ i64      ┆ str               ┆ f32            ┆ f32      ┆ f64          ┆ f64           ┆ f64                     ┆ f64             │
╞══════════╪═══════════════════╪════════════════╪══════════╪══════════════╪═══════════════╪═════════════════════════╪═════════════════╡
│ 20220901 ┆ lb2               ┆ 94.082535      ┆ 0.078611 ┆ 0.310082     ┆ 62.358631     ┆ -0.000949               ┆ -0.01206        │
│ 20220901 ┆ lb1               ┆ 93.123901      ┆ 0.082809 ┆ 0.299283     ┆ 65.180822     ┆ -0.001055               ┆ -0.012726       │
│ 20221201 ┆ lb1               ┆ 89.875885      ┆ 0.099424 ┆ 0.317168     ┆ 61.054224     ┆ -0.001658               ┆ -0.016651       │
│ 20221201 ┆ lb2               ┆ 89.943001      ┆ 0.097564 ┆ 0.31414      ┆ 58.531735     ┆ -0.001718               ┆ -0.017581       │
│ 20230301 ┆ lb1               ┆ 91.069489      ┆ 0.08348  ┆ 0.305958     ┆ 62.220793     ┆ -0.001435               ┆ -0.017169       │
│ 20230301 ┆ lb2               ┆ 90.974541      ┆ 0.084499 ┆ 0.301347     ┆ 60.322581     ┆ -0.001496               ┆ -0.01768        │
│ 20230601 ┆ lb1               ┆ 97.858047      ┆ 0.080248 ┆ 0.305968     ┆ 65.656832     ┆ -0.000326               ┆ -0.004064       │
│ 20230601 ┆ lb2               ┆ 97.740158      ┆ 0.080782 ┆ 0.301871     ┆ 64.001205     ┆ -0.000353               ┆ -0.004369       │
│ 20230901 ┆ lb2               ┆ 91.192917      ┆ 0.086928 ┆ 0.296112     ┆ 64.334041     ┆ -0.001369               ┆ -0.015727       │
│ 20230901 ┆ lb1               ┆ 90.922852      ┆ 0.087757 ┆ 0.293435     ┆ 64.786504     ┆ -0.001401               ┆ -0.015943       │
│ 20231201 ┆ lb2               ┆ 95.524498      ┆ 0.078057 ┆ 0.290532     ┆ 65.517938     ┆ -0.000683               ┆ -0.008745       │
│ 20231201 ┆ lb1               ┆ 94.82502       ┆ 0.079315 ┆ 0.287979     ┆ 65.579172     ┆ -0.000789               ┆ -0.009941       │
│ 20240301 ┆ lb1               ┆ 91.786819      ┆ 0.087478 ┆ 0.252229     ┆ 64.451297     ┆ -0.001274               ┆ -0.014549       │
│ 20240301 ┆ lb2               ┆ 91.633469      ┆ 0.086984 ┆ 0.25402      ┆ 64.438051     ┆ -0.001298               ┆ -0.014907       │
│ 20240601 ┆ lb1               ┆ 89.866348      ┆ 0.099556 ┆ 0.229163     ┆ 65.984556     ┆ -0.001536               ┆ -0.015402       │
│ 20240601 ┆ lb2               ┆ 89.857079      ┆ 0.099623 ┆ 0.223736     ┆ 64.854545     ┆ -0.001564               ┆ -0.015674       │
│ 20240901 ┆ lb1               ┆ 93.139954      ┆ 0.088492 ┆ 0.278813     ┆ 66.327969     ┆ -0.001034               ┆ -0.011675       │
│ 20240901 ┆ lb2               ┆ 92.684517      ┆ 0.087891 ┆ 0.276247     ┆ 64.466614     ┆ -0.001135               ┆ -0.012897       │
│ 20241201 ┆ lb2               ┆ 97.441971      ┆ 0.088168 ┆ 0.237336     ┆ 66.373582     ┆ -0.000385               ┆ -0.004369       │
│ 20241201 ┆ lb1               ┆ 97.023865      ┆ 0.089838 ┆ 0.235897     ┆ 66.56659      ┆ -0.000447               ┆ -0.004974       │
│ 20250301 ┆ lb2               ┆ 90.801476      ┆ 0.09403  ┆ 0.272796     ┆ 67.181023     ┆ -0.001369               ┆ -0.014542       │
│ 20250301 ┆ lb1               ┆ 90.42717       ┆ 0.094529 ┆ 0.274441     ┆ 68.54295      ┆ -0.001397               ┆ -0.014754       │
│ 20250601 ┆ lb2               ┆ 90.642319      ┆ 0.093516 ┆ 0.257402     ┆ 65.395664     ┆ -0.001431               ┆ -0.01528        │
│ 20250601 ┆ lb1               ┆ 90.380402      ┆ 0.094094 ┆ 0.257609     ┆ 66.507292     ┆ -0.001446               ┆ -0.01535        │
└──────────┴───────────────────┴────────────────┴──────────┴──────────────┴───────────────┴─────────────────────────┴─────────────────┘

--- TOP ELITE PER ERA DOMINANCE: lookback_key (5m) ---
shape: (2, 14)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┬─────────────┬─────────────┐
│ lookback_key ┆ dominance_sc ┆ elite_median ┆ elite_median ┆ elite_avg_m ┆ weighted_er ┆ recency_wei ┆ era_consist ┆ global_medi ┆ global_medi ┆ global_avg_ ┆ alpha_lift ┆ return_lift ┆ drawdown_ga │
│ (5m)         ┆ ore          ┆ _alpha       ┆ _return      ┆ ax_drawdown ┆ a_hits      ┆ ghted_era_c ┆ ency_score  ┆ an_alpha    ┆ an_return   ┆ max_drawdow ┆ ---        ┆ ---         ┆ p           │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ onsistency_ ┆ ---         ┆ ---         ┆ ---         ┆ n           ┆ f32        ┆ f32         ┆ ---         │
│ str          ┆ f64          ┆ f32          ┆ f32          ┆ f32         ┆ f64         ┆ score       ┆ f64         ┆ f32         ┆ f32         ┆ ---         ┆            ┆             ┆ f32         │
│              ┆              ┆              ┆              ┆             ┆             ┆ ---         ┆             ┆             ┆             ┆ f32         ┆            ┆             ┆             │
│              ┆              ┆              ┆              ┆             ┆             ┆ f64         ┆             ┆             ┆             ┆             ┆            ┆             ┆             │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╪═════════════╪═════════════╡
│ lb1          ┆ 0.520979     ┆ -0.000045    ┆ -0.000005    ┆ 0.076753    ┆ 4.777662    ┆ 0.942184    ┆ 0.916667    ┆ -0.012484   ┆ -0.00115    ┆ 0.089163    ┆ 0.012439   ┆ 0.001145    ┆ 0.01241     │
│ lb2          ┆ 0.479021     ┆ 0.001671     ┆ 0.000114     ┆ 0.074041    ┆ 4.777662    ┆ 0.942184    ┆ 0.916667    ┆ -0.012538   ┆ -0.001152   ┆ 0.088452    ┆ 0.014209   ┆ 0.001266    ┆ 0.014411    │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┴─────────────┴─────────────┘

--- LOOKBACK_KEY (15M) PERFORMANCE BY ERA (FLOOR: 40) ---
shape: (24, 8)
┌──────────┬────────────────────┬────────────────┬──────────┬──────────────┬───────────────┬─────────────────────────┬─────────────────┐
│ era_int  ┆ lookback_key (15m) ┆ median_balance ┆ avg_dd   ┆ avg_win_rate ┆ avg_total_pos ┆ median_return_per_trade ┆ alpha_per_trade │
│ ---      ┆ ---                ┆ ---            ┆ ---      ┆ ---          ┆ ---           ┆ ---                     ┆ ---             │
│ i64      ┆ str                ┆ f32            ┆ f32      ┆ f64          ┆ f64           ┆ f64                     ┆ f64             │
╞══════════╪════════════════════╪════════════════╪══════════╪══════════════╪═══════════════╪═════════════════════════╪═════════════════╡
│ 20220901 ┆ lb1                ┆ 93.436676      ┆ 0.082185 ┆ 0.307416     ┆ 65.585023     ┆ -0.001001               ┆ -0.012164       │
│ 20220901 ┆ lb2                ┆ 95.584702      ┆ 0.065962 ┆ 0.256519     ┆ 45.058333     ┆ -0.00098                ┆ -0.014841       │
│ 20221201 ┆ lb1                ┆ 89.876633      ┆ 0.099099 ┆ 0.32649      ┆ 62.200931     ┆ -0.001628               ┆ -0.016397       │
│ 20221201 ┆ lb2                ┆ 90.435883      ┆ 0.095199 ┆ 0.227511     ┆ 45.71831      ┆ -0.002092               ┆ -0.021929       │
│ 20230301 ┆ lb1                ┆ 90.707397      ┆ 0.084772 ┆ 0.309802     ┆ 63.449163     ┆ -0.001465               ┆ -0.017251       │
│ 20230301 ┆ lb2                ┆ 92.134491      ┆ 0.078139 ┆ 0.244418     ┆ 46.027778     ┆ -0.001709               ┆ -0.021832       │
│ 20230601 ┆ lb2                ┆ 100.383926     ┆ 0.069813 ┆ 0.286673     ┆ 52.15083      ┆ 0.000074                ┆ 0.001055        │
│ 20230601 ┆ lb1                ┆ 96.901161      ┆ 0.084303 ┆ 0.308595     ┆ 69.343048     ┆ -0.000447               ┆ -0.005299       │
│ 20230901 ┆ lb1                ┆ 91.311386      ┆ 0.08506  ┆ 0.306362     ┆ 69.549133     ┆ -0.001249               ┆ -0.014669       │
│ 20230901 ┆ lb2                ┆ 90.917595      ┆ 0.092915 ┆ 0.257417     ┆ 52.517483     ┆ -0.001729               ┆ -0.018581       │
│ 20231201 ┆ lb2                ┆ 96.254288      ┆ 0.07076  ┆ 0.26137      ┆ 52.283333     ┆ -0.000716               ┆ -0.010117       │
│ 20231201 ┆ lb1                ┆ 94.007355      ┆ 0.081913 ┆ 0.297501     ┆ 70.903587     ┆ -0.000845               ┆ -0.010309       │
│ 20240301 ┆ lb1                ┆ 91.370895      ┆ 0.087943 ┆ 0.258736     ┆ 68.643373     ┆ -0.001257               ┆ -0.014276       │
│ 20240301 ┆ lb2                ┆ 92.713799      ┆ 0.084912 ┆ 0.227872     ┆ 50.595238     ┆ -0.00144                ┆ -0.016935       │
│ 20240601 ┆ lb1                ┆ 89.80838       ┆ 0.101424 ┆ 0.224649     ┆ 70.143382     ┆ -0.001453               ┆ -0.014305       │
│ 20240601 ┆ lb2                ┆ 90.049698      ┆ 0.094264 ┆ 0.233809     ┆ 51.734756     ┆ -0.001923               ┆ -0.020364       │
│ 20240901 ┆ lb1                ┆ 94.01088       ┆ 0.087839 ┆ 0.275649     ┆ 69.470174     ┆ -0.000862               ┆ -0.009806       │
│ 20240901 ┆ lb2                ┆ 92.422287      ┆ 0.08909  ┆ 0.283618     ┆ 55.205722     ┆ -0.001373               ┆ -0.015386       │
│ 20241201 ┆ lb1                ┆ 98.131165      ┆ 0.086742 ┆ 0.24474      ┆ 71.518719     ┆ -0.000261               ┆ -0.003012       │
│ 20241201 ┆ lb2                ┆ 94.428894      ┆ 0.095122 ┆ 0.207242     ┆ 52.994203     ┆ -0.001051               ┆ -0.01104        │
│ 20250301 ┆ lb1                ┆ 91.035034      ┆ 0.093747 ┆ 0.281553     ┆ 73.215027     ┆ -0.001224               ┆ -0.013045       │
│ 20250301 ┆ lb2                ┆ 89.944183      ┆ 0.095365 ┆ 0.253244     ┆ 57.130283     ┆ -0.00176                ┆ -0.018425       │
│ 20250601 ┆ lb1                ┆ 90.160316      ┆ 0.094077 ┆ 0.248858     ┆ 69.702641     ┆ -0.001412               ┆ -0.014984       │
│ 20250601 ┆ lb2                ┆ 91.686699      ┆ 0.093144 ┆ 0.284905     ┆ 56.404901     ┆ -0.001474               ┆ -0.0158         │
└──────────┴────────────────────┴────────────────┴──────────┴──────────────┴───────────────┴─────────────────────────┴─────────────────┘

--- TOP ELITE PER ERA DOMINANCE: lookback_key (15m) ---
shape: (2, 14)
┌──────────────┬──────────────┬──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┬─────────────┬─────────────┐
│ lookback_key ┆ dominance_sc ┆ elite_median ┆ elite_median ┆ elite_avg_m ┆ weighted_er ┆ recency_wei ┆ era_consist ┆ global_medi ┆ global_medi ┆ global_avg_ ┆ alpha_lift ┆ return_lift ┆ drawdown_ga │
│ (15m)        ┆ ore          ┆ _alpha       ┆ _return      ┆ ax_drawdown ┆ a_hits      ┆ ghted_era_c ┆ ency_score  ┆ an_alpha    ┆ an_return   ┆ max_drawdow ┆ ---        ┆ ---         ┆ p           │
│ ---          ┆ ---          ┆ ---          ┆ ---          ┆ ---         ┆ ---         ┆ onsistency_ ┆ ---         ┆ ---         ┆ ---         ┆ n           ┆ f32        ┆ f32         ┆ ---         │
│ str          ┆ f64          ┆ f32          ┆ f32          ┆ f32         ┆ f64         ┆ score       ┆ f64         ┆ f32         ┆ f32         ┆ ---         ┆            ┆             ┆ f32         │
│              ┆              ┆              ┆              ┆             ┆             ┆ ---         ┆             ┆             ┆             ┆ f32         ┆            ┆             ┆             │
│              ┆              ┆              ┆              ┆             ┆             ┆ f64         ┆             ┆             ┆             ┆             ┆            ┆             ┆             │
╞══════════════╪══════════════╪══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╪═════════════╪═════════════╡
│ lb1          ┆ 0.834588     ┆ -0.000866    ┆ -0.000058    ┆ 0.077069    ┆ 4.777662    ┆ 0.942184    ┆ 0.916667    ┆ -0.011622   ┆ -0.001089   ┆ 0.089286    ┆ 0.010756   ┆ 0.001031    ┆ 0.012217    │
│ lb2          ┆ 0.165412     ┆ 0.006586     ┆ 0.000412     ┆ 0.067303    ┆ 2.260305    ┆ 0.445746    ┆ 0.5         ┆ -0.015364   ┆ -0.001397   ┆ 0.087434    ┆ 0.02195    ┆ 0.001809    ┆ 0.020131    │
└──────────────┴──────────────┴──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┴─────────────┴─────────────┘

KeyError: "Feature column not found: lookback_key (1h)\nTried: ['lookback_key (1h)', 'signal__lookback_key (1h)']\nAvailable signal columns: ['signal__lookback__15m__entry_lookback_units', 'signal__lookback__15m__timeframe', 'signal__lookback__5m__entry_lookback_units', 'signal__lookback__5m__timeframe', 'signal__stochastic__15m__d', 'signal__stochastic__15m__k', 'signal__stochastic__15m__s', 'signal__stochastic__15m__threshold_tolerance', 'signal__stochastic__15m__thresholds', 'signal__stochastic__15m__timeframe', 'signal__stochastic__5m__d', 'signal__stochastic__5m__k', 'signal__stochastic__5m__s', 'signal__stochastic__5m__threshold_tolerance', 'signal__stochastic__5m__thresholds', 'signal__stochastic__5m__timeframe']\nAvailable human-readable columns: ['stoch_key (5m)', 'lookback_key (5m)', 'stoch_key (15m)', 'lookback_key (15m)']"

In [ ]:
# --- Top 10 Feature Combinations by Consistency then Alpha ---
def top10_combinations(df_master: pl.DataFrame, feature_cols: list, trade_floor: int = 50, top_pct: float = 0.01, min_return: float = 0.05):
    """
    Find top 10 combinations of features based on era consistency and alpha per trade.
    """
    # --- 0. Filter by trade floor ---
    df_filtered = (
        df_master
        .filter(pl.col("total_pos") >= trade_floor)
        .filter(((pl.col("balance") - 100) / 100) >= min_return)
    )

    if df_filtered.is_empty():
        print(
            f"No strategies found with total_pos >= {trade_floor} "
            f"and return >= {min_return:.0%}"
        )
        return None, None

    # --- 1. Compute alpha_per_trade for all rows ---
    df_filtered = df_filtered.with_columns([
        (((pl.col("balance") - 100) / 100) / (pl.col("total_pos") + 1e-9) / (pl.col("max_drawdown") + 1e-9)).alias("alpha_per_trade")
    ])

    # --- 2. Compute top elite per era ---
    eras = df_filtered["era_int"].unique().to_list()
    top_rows_per_era = []

    for era in eras:
        era_df = df_filtered.filter(pl.col("era_int") == era)
        cutoff = max(1, int(len(era_df) * top_pct))
        top_rows = era_df.sort("alpha_per_trade", descending=True).head(cutoff)
        top_rows_per_era.append(top_rows)

    top_elite_per_era = pl.concat(top_rows_per_era)

    # --- 3. Compute era consistency score for each combination ---
    era_counts = (
        top_elite_per_era
        .group_by(feature_cols)
        .agg(pl.col("era_int").n_unique().alias("eras_found"))
        .with_columns((pl.col("eras_found") / len(eras)).alias("era_consistency_score"))
    )

    # --- 4. Merge consistency back to full dataframe ---
    df_with_consistency = df_filtered.join(era_counts, on=feature_cols, how="left").fill_null(0.0)

    # --- 5. Compute top 10 combinations ---
    top10_combos = df_with_consistency.sort(
        ["era_consistency_score", "alpha_per_trade"],
        descending=[True, True]
    ).select(feature_cols + ["era_consistency_score", "alpha_per_trade"]).unique().head(10)

    # --- 6. Compute alpha lift vs global median ---
    global_median_alpha = df_with_consistency["alpha_per_trade"].median()
    top10_combos = top10_combos.with_columns([
        (pl.col("alpha_per_trade") - global_median_alpha).alias("alpha_lift")
    ])

    print(f"\n--- TOP 10 FEATURE COMBINATIONS ({', '.join(feature_cols)}) ---")
    print(top10_combos.sort(["era_consistency_score", "alpha_per_trade"], descending=True))

    return top10_combos

# Example usage: combinations of ma_int, entry_lookback_units, exit_window_h
top10_combo = top10_combinations(
    df_master, 
    feature_cols=["ma_int", "entry_lookback_units", "exit_window_h", "trade_window_interval", "sl_decay_pct", "SL", "TP"]
)

--- TOP 10 FEATURE COMBINATIONS (ma_int, entry_lookback_units, exit_window_h, trade_window_interval, trailing_sl_pct, SL, TP) ---
shape: (10, 10)
┌────────┬──────────────────────┬───────────────┬───────────────────────┬─────────────────┬─────┬─────┬───────────────────────┬─────────────────┬────────────┐
│ ma_int ┆ entry_lookback_units ┆ exit_window_h ┆ trade_window_interval ┆ trailing_sl_pct ┆ SL  ┆ TP  ┆ era_consistency_score ┆ alpha_per_trade ┆ alpha_lift │
│ ---    ┆ ---                  ┆ ---           ┆ ---                   ┆ ---             ┆ --- ┆ --- ┆ ---                   ┆ ---             ┆ ---        │
│ f64    ┆ f64                  ┆ f64           ┆ f64                   ┆ f32             ┆ f32 ┆ f32 ┆ f64                   ┆ f32             ┆ f32        │
╞════════╪══════════════════════╪═══════════════╪═══════════════════════╪═════════════════╪═════╪═════╪═══════════════════════╪═════════════════╪════════════╡
│ 2.0    ┆ 2.0                  ┆ 4.0           ┆ 24.0                  ┆ 0.5             ┆ 0.2 ┆ 6.0 ┆ 0.166667              ┆ 0.031353        ┆ 0.004694   │
│ 0.0    ┆ 2.0                  ┆ 4.0           ┆ 24.0                  ┆ 0.2             ┆ 0.2 ┆ 3.5 ┆ 0.083333              ┆ 0.185246        ┆ 0.158587   │
│ 0.0    ┆ 2.0                  ┆ 24.0          ┆ 6.0                   ┆ 0.2             ┆ 0.2 ┆ 5.5 ┆ 0.0                   ┆ 0.049313        ┆ 0.022654   │
│ 3.0    ┆ 2.0                  ┆ 24.0          ┆ 6.0                   ┆ 0.2             ┆ 0.2 ┆ 4.0 ┆ 0.0                   ┆ 0.037938        ┆ 0.011279   │
│ 2.0    ┆ 2.0                  ┆ 24.0          ┆ 6.0                   ┆ 0.3             ┆ 0.2 ┆ 5.5 ┆ 0.0                   ┆ 0.018287        ┆ -0.008372  │
│ 1.0    ┆ 2.0                  ┆ 24.0          ┆ 6.0                   ┆ 0.3             ┆ 0.2 ┆ 3.0 ┆ 0.0                   ┆ 0.009104        ┆ -0.017555  │
│ 3.0    ┆ 2.0                  ┆ 4.0           ┆ 6.0                   ┆ 0.2             ┆ 0.2 ┆ 4.0 ┆ 0.0                   ┆ 0.009087        ┆ -0.017572  │
│ 3.0    ┆ 2.0                  ┆ 4.0           ┆ 6.0                   ┆ 0.2             ┆ 0.2 ┆ 6.0 ┆ 0.0                   ┆ 0.009008        ┆ -0.01765   │
│ 3.0    ┆ 2.0                  ┆ 4.0           ┆ 6.0                   ┆ 0.5             ┆ 0.2 ┆ 4.0 ┆ 0.0                   ┆ 0.00812         ┆ -0.018539  │
│ 0.0    ┆ 2.0                  ┆ 4.0           ┆ 6.0                   ┆ 0.2             ┆ 0.2 ┆ 6.0 ┆ 0.0                   ┆ 0.006247        ┆ -0.020412  │
└────────┴──────────────────────┴───────────────┴───────────────────────┴─────────────────┴─────┴─────┴───────────────────────┴─────────────────┴────────────┘

In [24]:
import polars as pl

def recursive_elite_selection(
    df_master: pl.DataFrame,
    feature_cols: list,
    top_pct: float = 0.1,
    trade_floor: int = 50
):
    """
    Recursive elite selection aligned with feature_performance logic:
    - Selection is PER ERA
    - Ranking metric: efficiency_per_trade
    - Feature value is chosen by:
        1) Era consistency
        2) Total top appearances (dominance)
        3) Efficiency per trade (tie-breaker only)
    """

    df_filtered = df_master.filter(pl.col("total_pos") >= trade_floor)
    elite_summary = []

    for feature in feature_cols:
        # --- 1. Compute efficiency_per_trade ---
        df_eff = df_filtered.with_columns([
            ((pl.col("balance") / (pl.col("max_drawdown") + 1e-9)) /
             (pl.col("total_pos") + 1e-9)).alias("efficiency_per_trade")
        ])

        eras = df_eff["era_int"].unique().to_list()
        top_rows_all_eras = []

        # --- 2. Select top X% PER ERA ---
        for era in eras:
            era_df = df_eff.filter(pl.col("era_int") == era)
            if era_df.is_empty():
                continue

            cutoff = max(1, int(era_df.height * top_pct))
            top_rows = (
                era_df
                .sort("efficiency_per_trade", descending=True)
                .head(cutoff)
            )
            top_rows_all_eras.append(top_rows)

        if not top_rows_all_eras:
            break

        top_elite = pl.concat(top_rows_all_eras)

        # --- 3. Era dominance scoring ---
        feature_score = (
            top_elite
            .group_by(feature)
            .agg([
                pl.col("era_int").n_unique().alias("eras_present"),
                pl.len().alias("total_top_instances"),
                pl.col("efficiency_per_trade").median().alias("median_eff_per_trade")
            ])
            .with_columns([
                (pl.col("eras_present") / len(eras)).alias("era_consistency_score")
            ])
            .sort(
                [
                    "era_consistency_score",   # must be consistent
                    "total_top_instances",     # dominance matters most
                    "median_eff_per_trade"     # quality as tie-breaker
                ],
                descending=[True, True, True]
            )
        )

        # --- 4. Pick dominant feature value ---
        top_value = feature_score[0, feature]

        elite_summary.append({
            "feature": feature,
            "top_value": top_value,
            "era_consistency": feature_score[0, "era_consistency_score"],
            "eras_present": feature_score[0, "eras_present"],
            "total_top_instances": feature_score[0, "total_top_instances"],
            "median_eff_per_trade": feature_score[0, "median_eff_per_trade"]
        })

        # --- 5. Filter for next recursion ---
        df_filtered = df_filtered.filter(pl.col(feature) == top_value)

        if df_filtered.height <= 1:
            break

    print("--- ELITE FEATURE COMBINATION SUMMARY (ERA DOMINANCE) ---")
    for e in elite_summary:
        print(e)

    print(f"\nFinal filtered dataset: {df_filtered.height} rows")
    return df_filtered, elite_summary

selected_features = [
    "stoch_key", "ma_int", "entry_lookback_units", 
    "exit_window_h", "TP", "SL", "sl_decay_pct", "use_sl_decay"
]

selected_features = [
    "trade_window_interval", "stoch_key", "ma_int", "entry_lookback_units", 
    "exit_window_h", "TP", "SL", "sl_decay_pct", "use_sl_decay"
]

df_elite, summary = recursive_elite_selection(df_master, selected_features)

--- ELITE FEATURE COMBINATION SUMMARY (ERA DOMINANCE) ---
{'feature': 'trade_window_interval', 'top_value': 12, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 15736, 'median_eff_per_trade': 115.45074462890625}
{'feature': 'stoch_key', 'top_value': 'k6_d6_s6_l30_u70', 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 4704, 'median_eff_per_trade': 128.41375732421875}
{'feature': 'ma_int', 'top_value': 3, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 1808, 'median_eff_per_trade': 129.90927124023438}
{'feature': 'entry_lookback_units', 'top_value': 2, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 479, 'median_eff_per_trade': 148.0550537109375}
{'feature': 'exit_window_h', 'top_value': 1, 'era_consistency': 0.9166666666666666, 'eras_present': 11, 'total_top_instances': 389, 'median_eff_per_trade': 142.051513671875}
{'feature': 'TP', 'top_value': 2.200000047683716, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 31, 'median_eff_per_trade': 171.4058380126953}
{'feature': 'SL', 'top_value': 0.6000000238418579, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 21, 'median_eff_per_trade': 176.99981689453125}
{'feature': 'sl_decay_pct', 'top_value': 0.30000001192092896, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 12, 'median_eff_per_trade': 181.03311157226562}
{'feature': 'use_sl_decay', 'top_value': True, 'era_consistency': 1.0, 'eras_present': 12, 'total_top_instances': 12, 'median_eff_per_trade': 181.03311157226562}

Final filtered dataset: 94 rows